version: '3.8'

services:
  db:
    image: postgres:16
    container_name: fichajes_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: horarios_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata_fichajes:/var/lib/postgresql/data

volumes:
  pgdata_fichajes:
